# Generated by Django 5.2.11 on 2026-02-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
